[EDU-765] CHORES Jwt authentication nodejs fix
ably/tutorials pull request #104
Opened 2022-07-21 16:32 UTC by fliptopbox

- repaced old logo with static asset
- replaced old UI with ably-ui like form
- updated JavaScript to ES6
- Added missing package.json

2022-07-28 12:03 UTC, fliptopbox commented
@marklewin for consistency i added you to review, since you have context of the textile file, that links to this repo.

2022-08-02 11:49 UTC, marklewin requested changes
Much better! Small typo in the UI though.

2022-08-02 11:49 UTC, marklewin commented on index.html
> +          alert("Client successfully connected Ably using JWT auth");
```suggestion
          alert("Client successfully connected to Ably using JWT auth");
```

2022-08-08 09:28 UTC, marklewin approved these changes
LGTM

2022-08-08 09:29 UTC, merged