Token Authentication, PHP samples
ably/tutorials pull request #5
Opened 2016-09-16 08:37 UTC by bartlomiejwereszczynski

2016-09-19 12:00 UTC, mattheworiordan commented on public/auth.php
> +        'clientId'  => $_COOKIE['username']
minor comment but extra space before `=>`

2016-09-19 12:05 UTC, mattheworiordan requested changes
Looks good, few comments to address

2016-09-19 12:05 UTC, mattheworiordan commented on public/ably.php
> +$ably = new \Ably\AblyRest(["key" => "{{ApiKey}}"]);
Out of interest why do you use this format here `["key" => "{{ApiKey}}"]` and in the other demo you passed only a key string, and in the tutorial itself you use a string too, see https://github.com/ably/docs/pull/164/commits/d0084781cf6ae58248c8b6a2b6f64a5b472d23f8#diff-a551a3cd350dc478774a772f537a027fR74

2016-09-19 12:05 UTC, mattheworiordan commented on public/auth.php
> +echo json_encode($ably->auth->createTokenRequest()->toArray());
Slightly inconsistent with the tutorial i.e. useful comment at https://github.com/ably/docs/pull/164/commits/d0084781cf6ae58248c8b6a2b6f64a5b472d23f8#diff-a551a3cd350dc478774a772f537a027fR248 is missing

2016-09-19 13:53 UTC, bartlomiejwereszczynski commented on public/ably.php
> +$ably = new \Ably\AblyRest(["key" => "{{ApiKey}}"]);
tutorial for ruby and node used similar syntax, and in docs i've copied that block from "history" tutorial, i'll update it to be correct with code sample

2016-09-19 13:53 UTC, bartlomiejwereszczynski commented on public/auth.php
> +echo json_encode($ably->auth->createTokenRequest()->toArray());
ok, i''l add that comment in code

2016-09-19 13:55 UTC, bartlomiejwereszczynski commented on public/auth.php
> +        'clientId'  => $_COOKIE['username']
formatting error, i was aiming to align both `=>` in same column, i'll fix it in second version

2016-09-20 07:10 UTC, bartlomiejwereszczynski commented
recreated version is available here: https://github.com/ably/tutorials/pull/9

2016-09-20 12:14 UTC, closed without merging