History, Python samples
ably/tutorials pull request #6
Opened 2016-09-16 12:52 UTC by bartlomiejwereszczynski

2016-09-16 16:14 UTC, mattheworiordan commented
Hi @bartlomiejwereszczynski thanks. Before I review, is there an associated docs PR that has the tutorial instructions I can review at the same time?

2016-09-16 16:26 UTC, bartlomiejwereszczynski commented
Hi @mattheworiordan , Yesy but since i had to start from `tutorials-in-php` (needed to change some blocks) i wanted to wait until you'll check them. You can view current progress in https://github.com/ably/docs/pull/164

2016-09-19 11:29 UTC, mattheworiordan commented on history.py
> +client = AblyRest('{{ApiKey}}')
This is missing the friendly error message for users who run this demo without setting the API Key.  It is important that the user is given an error message that makes it obvious they need to add the API to run the demo

2016-09-19 11:30 UTC, mattheworiordan commented on history.py
> +print('Retrieving channel...')
As with PHP, I don't think we should state retrieving a channel here.  We are instancing a stateless channel so not sure this adds anything but may in fact confuse users by making them think some server-side operation is done when instancing a REST channel.

2016-09-19 11:31 UTC, mattheworiordan commented on history.py
> +# this part is only for tutorial purposes, in real you can use same instance of $channel
We should remove this, but you are referencing the PHP variable $channel here anyway

2016-09-19 12:04 UTC, mattheworiordan requested changes
Thanks, looks good, just a few bits of feedback

2016-09-19 12:05 UTC, mattheworiordan commented on .gitignore
> +.idea
Isn't this ignore specific to your editor you are using?  If so, that should not be added to this repo and instead you should perhaps add to your global git ignore

2016-09-20 07:09 UTC, bartlomiejwereszczynski commented
recreated version is available here: https://github.com/ably/tutorials/pull/10

2016-09-20 12:30 UTC, mattheworiordan commented
@bartlomiejwereszczynski why is this up as another PR?  I would really prefer to review what you have fixed rather than review everything all over again?

2016-09-20 13:36 UTC, closed without merging