Node.js tutorial for Encryption API
ably/tutorials pull request #68
Opened 2019-08-15 13:22 UTC by vivekmore

https://docs.google.com/document/d/1776ZeKdIEF3j1m1ArB0xiJndOsaJMMmRHHXoO9eiMMw/edit

2019-09-13 11:09 UTC, Srushtika requested changes
Few changes, otherwise good to go.

2019-09-13 11:09 UTC, Srushtika commented on subscriber.js
> +const subscriber = realtime.channels.get('encrypted:messages', channelOpts);
It's worthing naming the variables representing the channel name with the word 'channel' in it. Like `msgChannel` . Same applies for the publisher

2019-09-13 11:09 UTC, Srushtika commented on package-lock.json
> +{
This file can be skipped from the commits

2019-09-13 11:34 UTC, vivekmore commented on subscriber.js
> +const subscriber = realtime.channels.get('encrypted:messages', channelOpts);
Won't that take away the clear distinction of purpose brought by calling `publisher` and `subscriber`?

Do you want me to name both as `msgChannel`?

2019-09-13 11:39 UTC, vivekmore commented on package-lock.json
> +{
Does this cause any issues being in the repo?

Generally package-lock.json are supposed committed in nodejs apps.
More details can be found here:
https://docs.npmjs.com/files/package-lock.json

2019-09-16 10:07 UTC, Srushtika commented on subscriber.js
> +const subscriber = realtime.channels.get('encrypted:messages', channelOpts);
> How about pubChannel & subChannel? OR publisherChannel and subscriberChannel?
This sounds good to me. I agree with the point about distinguishing them but they are both referring to the same channel. Moreover, calling them 'subscriber' isn confusing at it's supposed to refer to a channel and not the subscriber instance.

2019-09-16 10:07 UTC, Srushtika commented on package-lock.json
> +{
ok, sure, this can be retained then.

2019-09-18 01:26 UTC, vivekmore commented
Suggested changes are made

2019-09-18 09:17 UTC, merged

2019-09-18 10:46 UTC, vivekmore commented
For links in docs to work, please create tags against relevant commits as below
```
encryption-nodejs-step2
encryption-nodejs-step3
encryption-nodejs-step4
```